var princessInfo = {
	ann: {
		name: 'Anna',
		age: '18',
		height: '5\'3"',
		origin: 'Arendelle',
		foe: 'Hans, Duke of Weselton',
		truelove: 'Kristoff',
		favsong: '"Do You Want To Build a Snowman"',
		personality: 'daring, energetic, awkward, talkative',
		quote: '"You don\'t have to live in fear, \'cause for the first time in forever, I will be right here."',
		funfact: 'When Anna becomes completely frozen, you can see Elsa\'s signature snowflake on her iris.'
	},
	ari: {
		name: 'Ariel',
		age: '16',
		height: '5\'4"',
		origin: 'Atlantica',
		foe: 'Ursula',
		truelove: 'Prince Eric',
		favsong: '"Under the Sea"',
		personality: 'curious, kind, idealistic, bubbly, romantic',
		quote: '"I was a regular fish out of water."',
		funfact: 'Ariel has sung more songs than any other Disney character. Also, she is related to Hercules.'
	},
	aur: {
		name: 'Aurora aka "Sleeping Beauty" or "Briar Rose"',
		age: '16',
		height: '5\'6"',
		origin: 'the Eastern Kingdom',
		foe: 'Maleficent',
		truelove: 'Prince Phillip',
		favsong: '"Once Upon A Dream"',
		personality: 'graceful, dreamy, optimistic, gentle',
		quote: '"If you dream a thing more than once, it\'s sure to come true."',
		funfact: 'Aurora was the quietiest Disney princess; she only had 18 minutes of screen time and 18 dialogue lines.'
	},
	bel: {
		name: 'Belle',
		age: '17',
		height: '5\'5"',
		origin: 'a small French village',
		foe: 'Gaston',
		truelove: 'Prince Adam aka The Beast',
		favsong: '"Tale As Old As Time"',
		personality: 'outspoken, bookworm, selfless, curious',
		quote: '"I want adventure in the great wide somewhere."',
		funfact: 'Belle and the prince\'s dance at the end of the film is a reused animation from "Sleeping Beauty".'
	},
	cin: {
		name: 'Cinderella',
		age: '19',
		height: '5\'4"',
		origin: 'small, unnamed village',
		foe: 'Stepmother (Lady Tremaine)',
		truelove: 'Prince Charming',
		favsong: '"So This Is Love"',
		personality: 'kind, hard-working, intelligent, compassionate',
		quote: '"No matter how your heart is grieving, if you keep on believing, the dreams that you wish will come true."',
		funfact: 'Cinderella\'s shoe size is a women’s 4 1/2. She was also Walt Disney\'s favorite princess.'
	},
	els: {
		name: 'Elsa aka "the Snow Queen"',
		age: '21',
		height: '5\'3"',
		origin: 'Arendelle',
		foe: 'Hans, Duke of Weselton',
		truelove: 'no love interest',
		favsong: '"Let It Go"',
		personality: 'poised and reserved, independent, powerful',
		quote: '"The cold never bothered me anyway."',
		funfact: 'Elsa has more strands of hair than Rapunzel. She is also the second Disney princess to become Queen.'
	},
	esm: {
		name: 'Esmeralda',
		age: '22',
		height: '5\'7"',
		origin: 'Paris, France',
		foe: 'Claude Frollo',
		truelove: 'Captain Phoebus',
		favsong: '"God Help the Outcasts"',
		personality: 'flirtatious, stubborn, fearless, righteous',
		quote: '"You speak of justice, yet you are cruel to those most in need of your help."',
		funfact: 'Esmeralda is a gypsy who is skilled with tricks of illusion and deception. She is not actually a Disney princess.'
	},
	gis: {
		name: 'Giselle',
		age: '21',
		height: '5\'5"',
		origin: 'Kingdom of Andalasia',
		foe: 'Queen Narissa',
		truelove: 'Prince Edward',
		favsong: '"True Love\'s Kiss"',
		personality: 'optimistic, romantic, creative, eccentric',
		quote: '"But dreams do come true. And maybe something wonderful will happen!"',
		funfact: 'This film parallels scenes from "Snow White", "Beauty and the Beast", and "Snow White".'
	},
	jas: {
		name: 'Jasmine',
		age: '15',
		height: '5\'1"',
		origin: 'Agrabah',
		foe: 'Jafar',
		truelove: 'Aladdin',
		favsong: '"A Whole New World"',
		personality: 'sweet, sensitive, romantic, confident',
		quote: '"If I do marry, I want it to be for love."',
		funfact: 'Jasmine was the first Disney princess of color. She is also the only Disney princess who kissed a villainous character.'
	},
	kid: {
		name: 'Kidagakash Nedakh aka Kida',
		age: '8,500 years old',
		height: '5\'7"',
		origin: 'Empire of Atlantis',
		foe: 'Commander Lyle Tiberius Rourke',
		truelove: 'Milo Thatch',
		favsong: '"Where the Dream Takes You"',
		personality: 'fighter, kind, brave, resourceful',
		quote: '"We were once a great people. Now we live in ruins. The kings of our past would weep if they could see how far we have fallen."',
		funfact: 'Kida is the only multilingual princess. Although a princess by birth, Kida is not included in the Disney Princess franchise.'
	},
	meg: {
		name: 'Megara aka Meg',
		age: '18',
		height: '5\'7"',
		origin: 'Thebes, Greece',
		foe: 'Hades',
		truelove: 'Hercules',
		favsong: '"I Won\'t Say I\'m In Love"',
		personality: 'sassy, confident, sarcastic, dramatic',
		quote: '"I\'m a damsel. I\'m in distress. I can handle this. Have a nice day!"',
		funfact: 'Meg has a fear of heights. She is one of the few characters who has a nickname.'
	},
	mer: {
		name: 'Merida',
		age: '16',
		height: '5\'4"',
		origin: 'Kingdom DunBroch',
		foe: 'Mor\'du',
		truelove: 'no love interest',
		favsong: '"Touch the Sky"',
		personality: 'free-spirited, adventurous, tough, rebellious',
		quote: '"You control your destiny — you don\'t need magic to do it."',
		funfact: 'Merida is the only Disney princess with curly hair. She is also the only one with brothers.'
	},
	moa: {
		name: 'Moana',
		age: '16',
		height: '5\'4"',
		origin: 'Motunui',
		foe: 'Te Kā',
		truelove: 'no love interest',
		favsong: '"How Far I\'ll Go"',
		personality: 'headstrong, stubborn, daring, eccentric',
		quote: '"The ocean is a friend of mine."',
		funfact: 'When Moana wears red feathers, it symbolizes royalty. Rapunzel\'s hair in "Tangled" inspired the ocean in this film.'
	},
	mul: {
		name: 'Mulan',
		age: '16',
		height: '5\'3"',
		origin: 'China',
		foe: 'Chi-Fu',
		truelove: 'Li Shang',
		favsong: '"Reflection"',
		personality: 'fighter, opinionated, courageous, heroic',
		quote: '"If I wear a mask I can fool the world but I cannot fool my heart."',
		funfact: 'Mulan is the first Disney Princess who\'s not an actual princess, as she wasn\'t born from royalty. It took 700 animators, artists, and technicians to complete the film.  Mulan has the highest on-screen kill count of any Disney character, including villains.'
	},
	poc: {
		name: 'Pocahontas',
		age: '18',
		height: '5\'7"',
		origin: 'Jamestown, Virginia',
		foe: 'Governor Ratcliffe',
		truelove: 'John Smith',
		favsong: '"Colors of the Wind"',
		personality: 'free-spirited, romantic, open-minded, headstrong',
		quote: '"No matter what happens, I\'ll always be with you. Forever."',
		funfact: 'John Smith and Pocahontas\'s duet was cut from the original film because it was deemed "too boring".'
	},
	rap: {
		name: 'Rapunzel',
		age: '18',
		height: '5\'1"',
		origin: 'kingdom of Corona',
		foe: 'Mother Gothel',
		truelove: 'Eugene Fitzherbert aka Flynn Rider',
		favsong: '"I See the Light"',
		personality: 'artistic, highly perceptive, adventurous, feisty',
		quote: '"No, I won\'t stop. For every minute of the rest of my life I will fight."',
		funfact: 'Rapunzel has magical, golden hair with healing powers. She and Flynn have the largest age gap of any of the Disney Princess couples.'
	},
	sno: {
		name: 'Snow White',
		age: '14',
		height: '5\'2"',
		origin: 'the Fourth Kingdom/the Queen\'s Castle',
		foe: 'the Evil Queen',
		truelove: 'Prince Florian aka The Prince',
		favsong: '"Whistle While You Work"',
		personality: 'gentle, optimistic, sweet, innocent',
		quote: '"I\'m sure I\'ll get along somehow. Everything\'s going to be alright."',
		funfact: 'Snow White received a star on the Hollywood Walk of Fame.'
	},
	tia: {
		name: 'Tiana',
		age: '19',
		height: '5\'5"',
		origin: 'New Orleans, Louisiana',
		foe: 'Dr. Facilier',
		truelove: 'Prince Naveen',
		favsong: '"Almost There"',
		personality: 'intelligent, excellent cook, hardworking, passionate',
		quote: '"Fairy tales  can come true. You gotta make \'em happen; it all depends on you."',
		funfact: 'Tiana is the only Disney princess with a job. She is also left handed.'
	}
};
